services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  cqlsh-init:
    image: cassandra:latest
    container_name: cassandra-init
    networks:
      - cassandra-network
    volumes:
      - ./init.cql:/init.cql
    depends_on:
      cassandra:
        condition: service_healthy
    command: cqlsh cassandra -f /init.cql

networks:
  cassandra-network:
    driver: bridge
