services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./init.sh:/init.sh
    command: ["/bin/bash", "-c", "chmod +x /init.sh && /init.sh"]
